project:
  type: website
  output-dir: docs

website:
  title: "Ada Chibueze"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    mainfont: Georgia
    theme: Litera
    fontcolor: "#696765"
    linkcolor: "#7E7C7B"
    css: styles.css
    toc: true
    page-layout: full

editor: visual

