project:
  type: website
  output-dir: docs

website:
  title: "Ada Chibueze"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    background: dark
    left: Copyright 2024, Ada Chibueze

format:
  html:
    theme: 
      - Literia
      - styles.scss
    mainfont: Merriweather
    fontcolor: $brown
    css: styles.css
    toc: true
    page-layout: full
editor: visual

